config/routes.rb
Rails.application.routes.draw do


    
    root to: 'toppages#index'
    get 'ranking', to: 'ranks#index'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    get 'signup', to: 'users#new'
    
    get 'searchname', to: 'searches#searchname'
    get 'searchpre', to: 'searches#searchpre'
    
    resources :users, only: [:edit, :create, :update]
    resources :spots, only: [:edit, :create, :update, :new, :index, :show]do
        member do
            get :spot_review
        end
    end
    resources :reviews, only: [:edit, :update, :create, :new, :index, :destroy, :show]
end

app/models/spot.rb
class Spot < ApplicationRecord
    
validates :name, presence: true, length: { maximum: 30 }, uniqueness: true
validates :address, presence: true, length: {maximum: 50 }
validates :time_open, presence: true, length: { maximum: 30 }
validates :time_close, presence: true, length: { maximum: 30 }
validates :day_close, presence: true, length: { maximum: 30 }
validates :money, presence: true, length: { maximum: 30 }
validates :prefecture, presence: true
validates :image, presence: true
    mount_uploader :image, ImageUploader
    attr_accessor :average
    has_many :reviews
    belongs_to :user
    
    def self.searchname(search)
       if search
          Spot.where(['name LIKE ?', "%#{search}%"])
       else
           Spot.all
       end
    end
    
    def self.searchpre(search)
       if search
          Spot.where(['prefecture LIKE ?', "%#{search}%"])
       else
           Spot.all
       end
    end
    
    def average_point
       self.reviews.average(:point) 
    end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :require_user_logged_in, only: [:edit, :new, :index]
  def new
    @spot = current_user.spots.build
  end

  def create
    @spot = current_user.spots.build(spot_params)
    if @spot.save
      flash[:success] = '観光地を追加しました！'
      redirect_to root_url 
    else
      flash[:danger] = '観光地の追加に失敗しました'
      render 'spots/new'
    end
  end

  def edit
    @spot = current_user.spots.find(params[:id])
  end

  def update
    @spot = current_user.spots.find(params[:id])
    
    if @spot.update(spot_params_update)
      flash[:success] = '変更しました'
      redirect_to spots_url
    else
      flash[:danger] = '変更に失敗しました'
      render :edit
    end
  end

  def show
    @spot = Spot.find(params[:id])
    review_average(@spot)
  end

  def index
    @spots = current_user.spots.order(id: :desc).page(params[:page])
  end

   def spot_review
    @spot = Spot.find(params[:id])
    @reviews = @spot.reviews.order(id: :desc).page(params[:page])
   end
  
  private
  
  def spot_params
    params.require(:spot).permit(:name, :address, :prefecture, :time_open, :time_close, :day_close, :money, :image)
  end
  def spot_params_update
    params.require(:spot).permit(:name, :address, :prefecture, :time_open, :time_close, :day_close, :money)
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_spots.html.erb
<ul class="list-unstyled">
    <% spots.each do |spot| %>
        
      <div class= "row">
        <div class= "col-sm-5">
          <%= image_tag spot.image.thumb.url %>
        </div>
        <div class= "col-sm-7">
          <div class= "spot-block">
            <div>
              <h3><%= spot.name %></h3>
            </div>
            <p>ユーザー名 <%= spot.user.name %> </p>
           
            
            <a href="#" class="card-link"><%= link_to '詳細', spot_path(spot), class: 'btn btn-dark' %></a>
            <% if current_user == spot.user %>
             <a href="#" class="card-link"><%= link_to '変更', edit_spot_path(spot), class: 'btn btn-dark' %>
            <% end %>
          </div>
        </div>
      </div>
       
    <% end %>
    
    
</ul>

app/views/spots/edit.html.erb
<div class= "text-center">
    <h3 class = "text_font">観光地の編集</h3>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @spot, local: true) do |f| %>
      

      <div class="form-group">
        <%= f.label :name, '観光地の名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
          <%= f.label :prefecture, '都道府県' %>
          <%= f.select :prefecture,Schema.delivery_areas.keys, {}, {class: 'hoge'} %>
      </div>

      <div class="form-group">
        <%= f.label :address, '住所' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :time_open, '開店時間' %>
        <%= f.text_field :time_open, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :time_close, '閉店時間' %>
        <%= f.text_field :time_close, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :day_close, '定休日' %>
        <%= f.text_field :day_close, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :money, '予算' %>
        <%= f.text_field :money, class: 'form-control' %>
      </div>
      
 

      <%= f.submit '更新', class: 'btn btn-dark btn-block' %>
    <% end %>
    
  </div>

app/views/spots/index.html.erb
<div class= "text-center text_font">
    <h3>
        投稿したスポット一覧
    </h3>
</div>

<%= render 'spots', spots: @spots %>

app/views/spots/new.html.erb
<div class= "text-center">
    <h3 class = "text_font">観光地の追加</h3>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @spot, local: true) do |f| %>
      

      <div class="form-group">
        <%= f.label :name, '観光地の名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
          <%= f.label :prefecture, '都道府県' %>
          <%= f.select :prefecture,Schema.delivery_areas.keys, {}, {class: 'hoge'} %>
      </div>

      <div class="form-group">
        <%= f.label :address, '住所' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :time_open, '開店時間' %>
        <%= f.text_field :time_open, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :time_close, '閉店時間' %>
        <%= f.text_field :time_close, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :day_close, '定休日' %>
        <%= f.text_field :day_close, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :money, '予算' %>
        <%= f.text_field :money, class: 'form-control' %>
      </div>
      
      
        <%= f.file_field :image %>
       
      


      <%= f.submit '登録', class: 'btn btn-dark btn-block' %>
    <% end %>
    
  </div>
</div>
        

app/views/spots/show.html.erb
<div class= "text-center text_font">
    <h3><%= @spot.name %></h3>
</div>
<div class= "text-right">
    <p>レビュー平均：<%= @average_review %></p>
</div>

<ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="#" class="nav-link active">基本情報</a></li>
      <li class="nav-item"><%= link_to 'レビュー', spot_review_spot_path(@spot) %></li>

    </ul>
<div class= "row">
    <div class= "col-sm-6 offset-sm-2">
        <%= image_tag @spot.image.url %>
    </div>
</div>
        

<div class= "text-center spot_information">
    <p>名前:     <%= @spot.name %></p>
    <p>都道府県:   <%= @spot.prefecture %></p>
    <p>住所:     <%= @spot.address %></p>
    <p>開店時間:     <%= @spot.time_open %></p>
    <p>閉店時間:     <%= @spot.time_close %></p>
    <p>定休日:     <%= @spot.day_close %></p>
    <p>目安料金:     <%= @spot.money %></p>
</div>

app/views/spots/spot_review.html.erb
<div class= "text-center text_font">
    <h3><%= @spot.name %></h3>
</div>



    <ul class="nav nav-tabs nav-justified mb-3">
          <li class="nav-item"><%= link_to '基本情報', spot_path(@spot) %></li>
          <li class="nav-item"><a href="#" class="nav-link active">レビュー</a></li>
    
    </ul>


<div class= "text-center">
    <%= link_to 'レビューの投稿', new_review_path(spot_id: @spot.id), class: 'btn btn-dark btn-block' %>

<p class= "border_bottom"></p>

<%= render 'reviews/reviews', reviews: @reviews %>