config/routes.rb
Rails.application.routes.draw do


    
    root to: 'toppages#index'
    get 'ranking', to: 'ranks#index'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    get 'signup', to: 'users#new'
    
    get 'searchname', to: 'searches#searchname'
    get 'searchpre', to: 'searches#searchpre'
    
    resources :users, only: [:edit, :create, :update]
    resources :spots, only: [:edit, :create, :update, :new, :index, :show]do
        member do
            get :spot_review
        end
    end
    resources :reviews, only: [:edit, :update, :create, :new, :index, :destroy, :show]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :require_user_logged_in, only: [:edit, :new, :index, :destroy, :show]
  def edit
    
    @review = current_user.reviews.find(params[:id])
  end

  def update
    @review = current_user.reviews.find(params[:id])
    if @review.update(review_params)
      flash[:success] = 'レビューを更新しました！'
      redirect_to reviews_url
    else
      flash[:danger] = 'レビューの更新に失敗しました'
      render :edit
    end
  end
  
   def new
    @spot = params[:spot_id]
    @review = current_user.reviews.build
   end

  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      flash[:success] = 'レビューを追加しました！'
      redirect_to @review
    else
      flash[:danger] = 'レビューの追加に失敗しました'
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def index
    @reviews = current_user.reviews.order(id: :desc).page(params[:page])
  end

  def destroy
    @review = current_user.reviews.find(params[:id])
    @review.destroy
    
    flash[:success] = '削除しました'
    redirect_to reviews_url
  end
  
  private
  
  def review_params
    params.require(:review).permit(:title, :content, :point, :image, :spot_id)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
    
    
end

app/views/reviews/_reviews.html.erb
<ul class="list-unstyled">
    <% reviews.each.with_index(1) do |review| %>
        
      <div class= "row">
        
        <div class= "col-sm-5">
          
            <%= image_tag review.image.thumb.url %>
          
        </div>
        <div class= "col-sm-6">
          <div class= "review-block">
            <div>
              <h3><%= review.title %></h3>
            </div>
            <p>ユーザー名 <%= review.user.name %> 平均点数 <%= review.point %></p>
            <%= link_to '詳細', review_path(review), class: 'btn btn-dark' %>
            <% if current_user == review.user %>
              <%= link_to '変更', edit_review_path(review), class: 'btn btn-dark' %>
              <%= link_to '削除', review, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger' %>
            <% end %>
        </div>
        </div>
      </div>
        
    <% end %>
    
    
</ul>

app/views/reviews/edit.html.erb
<div class= "text-center">
    <h3 class = "text_font">レビューの変更</h3>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @review, local: true) do |f| %>
      

      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      
      <div class="form-group">
          <%= f.label :point, '点数' %>
          <%= f.number_field :point,min:1,max:5,step:1 %>
      </div>

      <div class="form-group">
        <%= f.label :content, '感想' %>
        <%= f.text_area :content, class: "form-control", size: "100x10" %>

      </div>
      
       
      

      
      
     


      <%= f.submit '更新完了して一覧に戻る', class: 'btn btn-dark btn-block' %>
    <% end %>
      
    
  </div>
</div>
        

app/views/reviews/index.html.erb
<div class= "text-center text_font">
    <h3>
        投稿したレビュー一覧
    </h3>
</div>

<%= render 'reviews', reviews: @reviews %>

app/views/reviews/new.html.erb
<div class= "text-center">
    <h3 class = "text_font">レビューの追加</h3>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @review, local: true) do |f| %>
      

      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      
      <div class="form-group">
          <%= f.label :point, '点数' %>
          <%= f.number_field :point,min:1,max:5,step:1 %>
      </div>

      <div class="form-group">
        <%= f.label :content, '感想' %>
        <%= f.text_area :content, class: "form-control", size: "100x10" %>

      </div>
      
      
      <div class="form-group">
        <%= f.file_field :image %>
       
      </div>
    
    <%= f.hidden_field :spot_id, :value => @spot %>
      
      
     


      <%= f.submit '登録', class: 'btn btn-dark btn-block' %>
    <% end %>
    
  </div>
</div>
        

app/views/reviews/show.html.erb
<div class="text-center">
    <h3>レビュー詳細</h3>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
        <h4>タイトル：<%= @review.title %></h4>
        
        <p class= "text-right">評価：<%= @review.point %>点</p>
        
        <p class="border-bottom"></p>
        <h5 class= "text-center">レビュー内容</h5>
        <p>
            <%= @review.content %>
        </p>
        
        
        
     <%= link_to '前に戻る', :back, class: 'btn btn-dark' %>
    </div>
</div>