config/routes.rb
Rails.application.routes.draw do


    
    root to: 'toppages#index'
    get 'ranking', to: 'ranks#index'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    get 'signup', to: 'users#new'
    
    get 'searchname', to: 'searches#searchname'
    get 'searchpre', to: 'searches#searchpre'
    
    resources :users, only: [:edit, :create, :update]
    resources :spots, only: [:edit, :create, :update, :new, :index, :show]do
        member do
            get :spot_review
        end
    end
    resources :reviews, only: [:edit, :update, :create, :new, :index, :destroy, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  
  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 500 } 
  validates :point, presence: true
  validates :image, presence: true
  
  belongs_to :user
  belongs_to :spot
  
mount_uploader :image, ImageUploader


  
end

app/models/schema.rb
class Schema < ApplicationRecord
   enum delivery_area:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
     沖縄県:47
   }

end

app/models/spot.rb
class Spot < ApplicationRecord
    
validates :name, presence: true, length: { maximum: 30 }, uniqueness: true
validates :address, presence: true, length: {maximum: 50 }
validates :time_open, presence: true, length: { maximum: 30 }
validates :time_close, presence: true, length: { maximum: 30 }
validates :day_close, presence: true, length: { maximum: 30 }
validates :money, presence: true, length: { maximum: 30 }
validates :prefecture, presence: true
validates :image, presence: true
    mount_uploader :image, ImageUploader
    attr_accessor :average
    has_many :reviews
    belongs_to :user
    
    def self.searchname(search)
       if search
          Spot.where(['name LIKE ?', "%#{search}%"])
       else
           Spot.all
       end
    end
    
    def self.searchpre(search)
       if search
          Spot.where(['prefecture LIKE ?', "%#{search}%"])
       else
           Spot.all
       end
    end
    
    def average_point
       self.reviews.average(:point) 
    end

end

app/models/user.rb
class User < ApplicationRecord
      before_save { self.email.downcase! }
      validates :name, presence: true, length: { maximum: 50 }
      validates :email, presence: true, length: { maximum: 255 },
                        format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                        uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :spots
    has_many :reviews
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
def index
  averages = Review.select("sport_id,avg(point) as avg").group(:sport_id)
      @spots = Spot.all.each do |spot|
        spot.average = spot.average_point
      end
     
     @spots = @spots.sort_by { |spot| spot.average }
end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :require_user_logged_in, only: [:edit, :new, :index, :destroy, :show]
  def edit
    
    @review = current_user.reviews.find(params[:id])
  end

  def update
    @review = current_user.reviews.find(params[:id])
    if @review.update(review_params)
      flash[:success] = 'レビューを更新しました！'
      redirect_to reviews_url
    else
      flash[:danger] = 'レビューの更新に失敗しました'
      render :edit
    end
  end
  
   def new
    @spot = params[:spot_id]
    @review = current_user.reviews.build
   end

  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      flash[:success] = 'レビューを追加しました！'
      redirect_to @review
    else
      flash[:danger] = 'レビューの追加に失敗しました'
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def index
    @reviews = current_user.reviews.order(id: :desc).page(params[:page])
  end

  def destroy
    @review = current_user.reviews.find(params[:id])
    @review.destroy
    
    flash[:success] = '削除しました'
    redirect_to reviews_url
  end
  
  private
  
  def review_params
    params.require(:review).permit(:title, :content, :point, :image, :spot_id)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def searchname
    @spots = Spot.searchname(params[:search])
  end
  
  def searchpre
    @spots = Spot.searchpre(params[:search])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end
  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :require_user_logged_in, only: [:edit, :new, :index]
  def new
    @spot = current_user.spots.build
  end

  def create
    @spot = current_user.spots.build(spot_params)
    if @spot.save
      flash[:success] = '観光地を追加しました！'
      redirect_to root_url 
    else
      flash[:danger] = '観光地の追加に失敗しました'
      render 'spots/new'
    end
  end

  def edit
    @spot = current_user.spots.find(params[:id])
  end

  def update
    @spot = current_user.spots.find(params[:id])
    
    if @spot.update(spot_params_update)
      flash[:success] = '変更しました'
      redirect_to spots_url
    else
      flash[:danger] = '変更に失敗しました'
      render :edit
    end
  end

  def show
    @spot = Spot.find(params[:id])
    review_average(@spot)
  end

  def index
    @spots = current_user.spots.order(id: :desc).page(params[:page])
  end

   def spot_review
    @spot = Spot.find(params[:id])
    @reviews = @spot.reviews.order(id: :desc).page(params[:page])
   end
  
  private
  
  def spot_params
    params.require(:spot).permit(:name, :address, :prefecture, :time_open, :time_close, :day_close, :money, :image)
  end
  def spot_params_update
    params.require(:spot).permit(:name, :address, :prefecture, :time_open, :time_close, :day_close, :money)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:edit]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params_create)
    if @user.save
      flash[:success] = '登録完了しました'
      redirect_to root_url
    else
      flash[:danger] = '登録に失敗しました'
      render :new
    end
  end
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params_update)
      flash[:success] = '更新に成功しました'
      redirect_to root_url
    else
      flash[:danger] = '更新に失敗しました'
      render :edit
    end
  end
  
  private
  
  def user_params_create
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def user_params_update
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
    
    
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
  
  def review_average(spot)
       @average_review = spot.reviews.average(:point)
    end
  

end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
    <% unless logged_in? %>
        <nav class = "navbar navbar-expand-sm navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Photrabel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                 <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item"><%= link_to '新規登録', signup_path, class: ' nav-link ' %></li>
                    <li class="nav-item"><%= link_to 'ログイン', login_path, class: ' nav-link ' %></li>
                </ul>
            </div>
        </nav>
    <% else %>
        <nav class = "navbar navbar-expand-sm navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Photrabel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                 <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                    　<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">メニュー</a>
                    　<ul class="dropdown-menu dropdown-menu-right">
                          <li class="dropdown-item"><%= link_to 'ユーザー詳細', edit_user_path(current_user) %></li>
                          <li class="dropdown-item"><%= link_to '投稿したレビュー一覧' , reviews_path %></li>
                          <li class="dropdown-item"><%= link_to '投稿したスポット一覧', spots_path %></li>
                          <li class="dropdown-divider"></li>
                          <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                    　</ul>
                    </li>
                </ul>
            </div>
        </nav>
    <% end %>
    
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Microposts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
    

  </body>
</html>